### ISSUE TITLE
Vulnerability in dash copay?

### ISSUE THREAD

**Issue by InhumanPerfection** [dashevo/dash-copay#104]
https://github.com/dominictarr/event-stream/issues/116#issuecomment-441744514

> I got it decoded. Package description "A Secure Bitcoin Wallet". The targeted package is: https://www.npmjs.com/package/copay-dash

https://github.com/dominictarr/event-stream/issues/116#issuecomment-441749105

> So, for people who try to understand what the malicious payload is doing: it's basically crawling your dependencies for a peer dependency on the package copay-dash, and it's an attack basically crafted towards this package.
> If your overall application has both this malicious package and "copay-dash", then it's going to try stealing the bitcoins stored in it.

**Comment by nmarley** [comment]
Hi, thanks for reporting. This vulnerable package is 2 years old and not a supported package. One of our developers still has access and has added a warning not to use this. It was never our current Dash CoPay lib, which is actually named dash-copay (note the reversal).

These are separate NPM packages (`copay-dash` !== `dash-copay`). The latter is the supported one and not affected by this particular vulnerability, because the particular search string doesn't exist in the supported NPM package description.
